import argparse
import csv
import html
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

DEFAULT_EXPORT = "/Users/carsonhedlund/Desktop/atlas-batch/routes.csv"
JUNK_NAME = "way/421156644"
NAME_START_MAX_MI = 0.25
GEOM_START_MAX_MI = 0.05

CSV_FIELDS = [
    "supabase_id", "engine_route_id", "match_by", "start_dist_mi", "supabase_name",
    "name_fix", "old_distance", "new_distance", "old_gain", "new_gain",
    "bikes_allowed", "dogs_allowed", "park_name", "status",
]


def name_key(s):
    return re.sub(r"[^a-z0-9]", "", html.unescape(s or "").lower())


def haversine_miles(a, b):
    r = 3958.8
    p1, p2 = math.radians(a[0]), math.radians(b[0])
    dp, dl = p2 - p1, math.radians(b[1] - a[1])
    h = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(min(1.0, math.sqrt(h)))


def read_export(path):
    csv.field_size_limit(sys.maxsize)
    rows = []
    with open(path, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            coords = json.loads(r["coordinates"]) if r.get("coordinates") else []
            r["distance"] = float(r["distance"] or 0)
            r["elevation_gain"] = float(r["elevation_gain"] or 0)
            r["start"] = (coords[0][1], coords[0][0]) if coords else None
            rows.append(r)
    return rows


def match_routes(engine, sb):
    by_name = {}
    for i, r in enumerate(sb):
        by_name.setdefault(name_key(r["name"]), []).append(i)
    used, out = set(), {}
    for ei, e in enumerate(engine):
        cands = [i for i in by_name.get(name_key(e["name"]), []) if i not in used and sb[i]["start"]]
        cands.sort(key=lambda i: haversine_miles(e["_start_point"], sb[i]["start"]))
        if cands:
            d = haversine_miles(e["_start_point"], sb[cands[0]]["start"])
            used.add(cands[0])
            out[ei] = (cands[0], "name+start" if d <= NAME_START_MAX_MI else "name_only_review", d)
            continue
        geo = []
        for i, r in enumerate(sb):
            if i in used or not r["start"]:
                continue
            d = haversine_miles(e["_start_point"], r["start"])
            if d < GEOM_START_MAX_MI and abs(e["distance_miles"] - r["distance"]) <= 0.1 * max(1.0, r["distance"]):
                geo.append((d, i))
        if geo:
            geo.sort()
            used.add(geo[0][1])
            out[ei] = (geo[0][1], "geometry", geo[0][0])
    return out


def q(v):
    return "'" + str(v).replace("'", "''") + "'"


def build(engine, sb):
    matches = match_routes(engine, sb)
    rows = []
    for ei, (si, how, d) in sorted(matches.items(), key=lambda kv: kv[1][0]):
        e, r = engine[ei], sb[si]
        dog = e.get("osm_dog_allowed")
        rows.append({
            "supabase_id": r["id"],
            "engine_route_id": e["route_id"],
            "match_by": how,
            "start_dist_mi": round(d, 3),
            "supabase_name": r["name"],
            "name_fix": html.unescape(r["name"]) if html.unescape(r["name"]) != r["name"] else "",
            "old_distance": r["distance"],
            "new_distance": e["distance_miles"],
            "old_gain": r["elevation_gain"],
            "new_gain": e["elevation_gain"],
            "bikes_allowed": "" if e.get("osm_bicycle_legal") is None else str(bool(e["osm_bicycle_legal"])).lower(),
            "dogs_allowed": "" if dog is None else str(bool(dog)).lower(),
            "park_name": e.get("osm_park_name") or "",
            "status": "review" if how == "name_only_review" else "update",
        })
    matched_ids = {r["supabase_id"] for r in rows}
    fixes = [r for r in sb if html.unescape(r["name"]) != r["name"]]
    junk = [r for r in sb if html.unescape(r["name"]).strip() == JUNK_NAME]
    return rows, fixes, junk, matched_ids


def build_sql(rows, fixes, junk):
    ids = [r["supabase_id"] for r in rows]
    L = ["-- Generated by scripts/sync_supabase.py. Review before running. Not executed by the generator.",
         "-- Run the preview first, then the transaction.", "",
         "-- 0. PREVIEW (read-only): current values of every row the UPDATEs below will touch.",
         "SELECT id, name, distance, elevation_gain, bikes_allowed, dogs_allowed",
         "FROM routes WHERE id IN (" + ", ".join(q(i) for i in ids) + ")", "ORDER BY name;", "",
         "BEGIN;", "",
         "-- 1. Schema: engine link key and park name (both nullable).",
         "ALTER TABLE routes ADD COLUMN IF NOT EXISTS engine_route_id text;",
         "ALTER TABLE routes ADD COLUMN IF NOT EXISTS park_name text;",
         "CREATE UNIQUE INDEX IF NOT EXISTS routes_engine_route_id_uidx ON routes (engine_route_id) WHERE engine_route_id IS NOT NULL;",
         "", "-- 2. Name unescape fix (HTML entities in stored names), all rows."]
    for r in fixes:
        L.append(f"UPDATE routes SET name = {q(html.unescape(r['name']))} WHERE id = {q(r['id'])};")
    L += ["", "-- 3. Metrics from GPX (engine loader). distance in miles, elevation_gain in feet.",
          "-- elevation_loss is not produced by the engine loader and is left unchanged.",
          "-- Rows marked REVIEW matched by name but the start point is over 0.25 mi away; they are commented out."]
    for r in rows:
        sets = [f"engine_route_id = {q(r['engine_route_id'])}", f"distance = {r['new_distance']}",
                f"elevation_gain = {int(r['new_gain'])}"]
        if r["bikes_allowed"]:
            sets.append(f"bikes_allowed = {r['bikes_allowed']}")
        if r["dogs_allowed"]:
            sets.append(f"dogs_allowed = {r['dogs_allowed']}")
        if r["park_name"]:
            sets.append(f"park_name = {q(r['park_name'])}")
        stmt = f"UPDATE routes SET {', '.join(sets)} WHERE id = {q(r['supabase_id'])};"
        L.append(("-- REVIEW " + stmt) if r["status"] == "review" else stmt)
    L += ["", "-- 4. Junk Overpass export row. Commented out: uncomment only after review."]
    for r in junk:
        L.append(f"-- DELETE FROM routes WHERE id = {q(r['id'])};  -- {r['name']}")
    if not junk:
        L.append(f"-- (no row named {JUNK_NAME} found in the export)")
    L += ["", "-- 5. Sanity check inside the transaction (expect the number of non-review updates).",
          "SELECT count(*) AS linked FROM routes WHERE engine_route_id IS NOT NULL;", "", "COMMIT;", ""]
    return "\n".join(L)


def write_outputs(rows, sql, out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "supabase_sync.sql").write_text(sql, encoding="utf-8")
    with open(out_dir / "supabase_sync.csv", "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=CSV_FIELDS)
        w.writeheader()
        w.writerows(rows)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--export", default=DEFAULT_EXPORT)
    ap.add_argument("--gpx-dir", default=str(ROOT / "data" / "gpx"))
    ap.add_argument("--out-dir", default=str(ROOT / "out"))
    a = ap.parse_args(argv)
    from gpx_loader import load_routes_from_gpx_dir
    engine = load_routes_from_gpx_dir(a.gpx_dir)
    sb = read_export(a.export)
    rows, fixes, junk, _ = build(engine, sb)
    write_outputs(rows, build_sql(rows, fixes, junk), a.out_dir)
    print(f"engine={len(engine)} supabase={len(sb)} matched={len(rows)} "
          f"review={sum(r['status']=='review' for r in rows)} name_fixes={len(fixes)} junk={len(junk)}")


if __name__ == "__main__":
    main()
